/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BannerBox: typeof import('./src/components/BannerBox.vue')['default']
    FooterBox: typeof import('./src/components/FooterBox.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    ImgBox: typeof import('./src/components/ImgBox.vue')['default']
    InfoBox: typeof import('./src/components/InfoBox.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor.vue')['default']
    MdViewer: typeof import('./src/components/MdViewer.vue')['default']
    NoteItem: typeof import('./src/components/NoteItem.vue')['default']
    NoteList: typeof import('./src/components/NoteList.vue')['default']
    PopForm: typeof import('./src/components/PopForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineList: typeof import('./src/components/TimelineList.vue')['default']
  }
}
